# Generated by Django 4.0.3 on 2022-04-11 10:43

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dorg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krat', models.CharField(max_length=50, verbose_name='Краткое название организации')),
                ('poln', models.CharField(blank=True, max_length=500, verbose_name='Полное название организации')),
                ('tel1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона секретариата')),
                ('tel2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона приемной')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Электронная почта')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Электронный адрес')),
                ('adr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Почтовый адрес')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('krat',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(blank=True, choices=[(False, 'Вне сети'), (True, 'В сети')], default=False, verbose_name='Статус')),
                ('last_activity', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время последней активности')),
                ('color', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Цвет профиля')),
                ('user_agreement', models.DateField(blank=True, null=True, verbose_name='Дата ознакомления с пользовательским соглашением и согласием на обработку персональных данных')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.dorg', verbose_name='Организация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ('-last_activity',),
            },
        ),
    ]
