# Generated by Django 4.0.3 on 2022-04-11 10:43

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dcolors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MainStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1000, null=True, verbose_name='Пользователь')),
                ('url', models.URLField(null=True, verbose_name='URL')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='IP пользователя')),
                ('browser', models.CharField(max_length=1000, null=True, verbose_name='Браузер пользователя')),
                ('session_key', models.CharField(max_length=1000, null=True, verbose_name='Ключ сессии')),
                ('dactivity', models.DateTimeField(null=True, verbose_name='Время активности')),
            ],
            options={
                'ordering': ('dactivity',),
            },
        ),
        migrations.CreateModel(
            name='QueryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.TextField(verbose_name='Фильтры')),
                ('app_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_statistics.mainstatistics')),
            ],
        ),
    ]
